{
  "procurement_categories": {
    "公園": "D",
    "綠美化": "D",
    "景觀": "D",
    "植樹": "D",
    "造林": "D",
    "紅樹林": "D",
    "濕地": "D",
    "生態": "D",
    "新建工程": "A",
    "興建": "A",
    "改建": "A",
    "增建": "A",
    "古蹟": "A",
    "修復": "A",
    "校舍": "A",
    "活動中心": "A",
    "長照大樓": "A",
    "青年住宅": "A",
    "水利工程": "B",
    "排水": "B",
    "滯洪": "B",
    "抽水站": "B",
    "污水": "B",
    "下水道": "B",
    "堤岸": "B",
    "橋梁": "B",
    "裝修工程": "E",
    "設備": "E",
    "場館": "E",
    "整修": "E",
    "交通改善": "C",
    "標誌標線": "C",
    "人行": "C",
    "自行車": "C",
    "電動車": "C",
    "公車": "C",
    "評估": "F",
    "規劃": "F",
    "顧問": "F",
    "系統建置": "F",
    "監測": "F",
    "電梯": "A",
    "冷氣": "A",
    "空調": "A",
    "冷凍": "A",
    "疫苗": "A",
    "生物製劑": "A",
    "營運": "E",
    "管理": "F",
    "盤查": "F"
  },
  "keyword_triggers": [
    {
      "keyword": "LED",
      "suggested_item": "LED燈具全面汰換",
      "code": "1-7",
      "category_id": "E",
      "sub_id": "E1",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_001"
    },
    {
      "keyword": "路燈",
      "suggested_item": "道路照明LED燈具汰換",
      "code": "住商-3",
      "category_id": "C",
      "sub_id": "C1",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_002"
    },
    {
      "keyword": "電動車",
      "suggested_item": "電動公車或電動公務車採購",
      "code": "運輸-2",
      "category_id": "C",
      "sub_id": "C2",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [
        "電動公車",
        "電動巴士",
        "電動公務車"
      ],
      "negative_context": [
        "機車",
        "摩托車",
        "輕型"
      ],
      "learning_tip": "",
      "trigger_id": "KW_003"
    },
    {
      "keyword": "充電",
      "suggested_item": "停車場電動車充電樁設置",
      "code": "運輸-2",
      "category_id": "C",
      "sub_id": "C1",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_004"
    },
    {
      "keyword": "滯洪池",
      "suggested_item": "滯洪池、抽水站建置與防洪改善",
      "code": "調適-水",
      "category_id": "B",
      "sub_id": "B1",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [
        "蓄洪池",
        "滯洪",
        "滯洪設施",
        "蓄洪"
      ],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_005"
    },
    {
      "keyword": "抽水站",
      "suggested_item": "滯洪池、抽水站建置與防洪改善",
      "code": "調適-水",
      "category_id": "B",
      "sub_id": "B1",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_006"
    },
    {
      "keyword": "排水",
      "suggested_item": "排水系統清淤與維護管理",
      "code": "調適-水",
      "category_id": "B",
      "sub_id": "B1",
      "_match_type": "exact",
      "weight": 0.6,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [
        2
      ],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_007"
    },
    {
      "keyword": "污水",
      "suggested_item": "污水下水道建置與用戶接管",
      "code": "環境-1",
      "category_id": "B",
      "sub_id": "B2",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_008"
    },
    {
      "keyword": "下水道",
      "suggested_item": "污水下水道建置與用戶接管",
      "code": "環境-1",
      "category_id": "B",
      "sub_id": "B2",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_009"
    },
    {
      "keyword": "綠建築",
      "suggested_item": "取得綠建築或建築能效(BERS)標章",
      "code": "住商-1",
      "category_id": "A",
      "sub_id": "A1",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_010"
    },
    {
      "keyword": "長照",
      "suggested_item": "近零碳建築技術(nZEB)",
      "code": "住商-1",
      "category_id": "A",
      "sub_id": "A1",
      "_match_type": "exact",
      "weight": 0.6,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [
        4
      ],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_011"
    },
    {
      "keyword": "長照衛福大樓",
      "suggested_item": "近零碳建築技術(nZEB)",
      "code": "住商-1",
      "category_id": "A",
      "sub_id": "A1",
      "_match_type": "exact",
      "weight": 0.6,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [
        4
      ],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_012"
    },
    {
      "keyword": "青年住宅",
      "suggested_item": "近零碳建築技術(nZEB)",
      "code": "住商-1",
      "category_id": "A",
      "sub_id": "A1",
      "_match_type": "exact",
      "weight": 0.6,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [
        4
      ],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_013"
    },
    {
      "keyword": "托嬰",
      "suggested_item": "場館室內裝修（通用節能檢核）",
      "code": "住商-4",
      "category_id": "E",
      "sub_id": "E2",
      "_match_type": "exact",
      "weight": 0.6,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [
        4
      ],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_014"
    },
    {
      "keyword": "太陽能",
      "suggested_item": "屋頂太陽能光電設置",
      "code": "能源-1",
      "category_id": "E",
      "sub_id": "E1",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [
        5
      ],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_015"
    },
    {
      "keyword": "光電",
      "suggested_item": "屋頂太陽能光電設置",
      "code": "能源-1",
      "category_id": "E",
      "sub_id": "E1",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [
        5
      ],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_016"
    },
    {
      "keyword": "植樹",
      "suggested_item": "植樹造林或都市綠化",
      "code": "農業-5",
      "category_id": "D",
      "sub_id": "D1",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "環境部認定標準：非以造林為目的之一般景觀植栽（如路燈、公園邊緣綠化）不計入碳匯。建議本案優先確認是否具備降溫或城市生態廊道價值。",
      "trigger_id": "KW_017"
    },
    {
      "keyword": "造林",
      "suggested_item": "植樹造林或都市綠化",
      "code": "農業-5",
      "category_id": "D",
      "sub_id": "D1",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "環境部認定標準：須符合規模限制與特定方法學（如森林經營）方可計入碳匯。請檢點本案是否為特定造林計畫而非例行綠美化。",
      "trigger_id": "KW_018"
    },
    {
      "keyword": "公園",
      "suggested_item": "植樹造林或都市綠化",
      "code": "農業-5",
      "category_id": "D",
      "sub_id": "D1",
      "_match_type": "exact",
      "weight": 0.4,
      "purity_hint": "P4_LOW",
      "anti_pattern_ids": [
        3
      ],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_019"
    },
    {
      "keyword": "紅樹林",
      "suggested_item": "濕地、紅樹林或棲地復育",
      "code": "農業-7",
      "category_id": "D",
      "sub_id": "D1",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_020"
    },
    {
      "keyword": "濕地",
      "suggested_item": "濕地、紅樹林或棲地復育",
      "code": "農業-7",
      "category_id": "D",
      "sub_id": "D1",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_021"
    },
    {
      "keyword": "人行空間",
      "suggested_item": "建置友善行人空間或自行車道",
      "code": "運輸-1",
      "category_id": "C",
      "sub_id": "C1",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_022"
    },
    {
      "keyword": "自行車道",
      "suggested_item": "建置友善行人空間或自行車道",
      "code": "運輸-1",
      "category_id": "C",
      "sub_id": "C1",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_023"
    },
    {
      "keyword": "公共自行車",
      "suggested_item": "公共自行車站點擴建",
      "code": "運輸-1",
      "category_id": "C",
      "sub_id": "C1",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_024"
    },
    {
      "keyword": "智慧站牌",
      "suggested_item": "導入大眾運輸智慧化系統（智慧站牌）",
      "code": "運輸-3",
      "category_id": "C",
      "sub_id": "C2",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_025"
    },
    {
      "keyword": "淨零",
      "suggested_item": "縣市層級淨零/氣候調適計畫研擬",
      "code": "淨零教育-1",
      "category_id": "F",
      "sub_id": "F1",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_026"
    },
    {
      "keyword": "碳盤查",
      "suggested_item": "組織碳盤查或碳足跡評估",
      "code": "淨零教育-2",
      "category_id": "F",
      "sub_id": "F1",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_027"
    },
    {
      "keyword": "監測",
      "suggested_item": "空氣品質或溫室氣體監測系統",
      "code": "環境-4",
      "category_id": "F",
      "sub_id": "F2",
      "_match_type": "exact",
      "weight": 0.7,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [
        8
      ],
      "synonyms": [],
      "negative_context": [
        "資安",
        "公文",
        "人事",
        "監視器",
        "薪資",
        "財務",
        "防毒"
      ],
      "learning_tip": "監測案件請確認是否涉及氣象、水位、淹水預警、溫室氣體或氣候風險參數。",
      "trigger_id": "KW_028"
    },
    {
      "keyword": "空調",
      "suggested_item": "高能效空調系統更新",
      "code": "住商-4",
      "category_id": "E",
      "sub_id": "E1",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_029"
    },
    {
      "keyword": "冷氣",
      "suggested_item": "高能效空調系統更新",
      "code": "住商-4",
      "category_id": "E",
      "sub_id": "E1",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_030"
    },
    {
      "keyword": "節能",
      "suggested_item": "智慧能源管理系統（BEMS）",
      "code": "住商-5",
      "category_id": "E",
      "sub_id": "E1",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_031"
    },
    {
      "keyword": "透水",
      "suggested_item": "廣場透水鋪面改善",
      "code": "調適-水",
      "category_id": "D",
      "sub_id": "D2",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_032"
    },
    {
      "keyword": "底渣",
      "suggested_item": "廢水污泥再利用或資源化",
      "code": "環境-5",
      "category_id": "B",
      "sub_id": "B2",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_033"
    },
    {
      "keyword": "資源回收",
      "suggested_item": "",
      "code": "concept",
      "category_id": "",
      "sub_id": "",
      "_match_type": "exact",
      "weight": 0.4,
      "purity_hint": "P4_LOW",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [
        "宣導",
        "活動",
        "教育",
        "訓練"
      ],
      "learning_tip": "命中本詞僅代表循環概念，請確認是否有具體資源化設施、減廢工程或可量化減碳作為。",
      "trigger_id": "KW_034",
      "match_type": "concept_trigger"
    },
    {
      "keyword": "古蹟",
      "suggested_item": "古蹟或歷史建築修復（文資保存）",
      "code": "住商-6",
      "category_id": "A",
      "sub_id": "A1",
      "_match_type": "exact",
      "weight": 0.6,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_035"
    },
    {
      "keyword": "修復",
      "suggested_item": "古蹟或歷史建築修復（文資保存）",
      "code": "concept",
      "category_id": "",
      "sub_id": "",
      "_match_type": "exact",
      "weight": 0.5,
      "purity_hint": "P4_LOW",
      "anti_pattern_ids": [
        4
      ],
      "synonyms": [],
      "negative_context": [
        "道路",
        "路面"
      ],
      "learning_tip": "命中本詞僅代表可能涉及改造工程，需確認是否具節能、低碳材料或調適設計，才可列為氣候預算。",
      "trigger_id": "KW_036",
      "match_type": "concept_trigger"
    },
    {
      "keyword": "災修",
      "suggested_item": "滯洪池、抽水站建置與防洪改善",
      "code": "調適-水",
      "category_id": "B",
      "sub_id": "B1",
      "_match_type": "exact",
      "weight": 0.6,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [
        2
      ],
      "synonyms": [],
      "negative_context": [
        "道路",
        "路基",
        "路面",
        "路基工"
      ],
      "learning_tip": "災修案件大量為道路或検查工程，不具備調適意義。請確認全案是否具備防洪或氣候韌性角度再訄定為氣候預算。",
      "trigger_id": "KW_037"
    },
    {
      "keyword": "防洪",
      "suggested_item": "滯洪池、抽水站建置與防洪改善",
      "code": "調適-水",
      "category_id": "B",
      "sub_id": "B1",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_038"
    },
    {
      "keyword": "道路改善",
      "suggested_item": "道路熱島效應改善（透水鋪面、遮蔭）",
      "code": "運輸-5",
      "category_id": "A",
      "sub_id": "A2",
      "_match_type": "exact",
      "weight": 0.6,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [
        1
      ],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_039"
    },
    {
      "keyword": "環境教育",
      "suggested_item": "節能減碳推廣教育宣導計畫",
      "code": "淨零教育-1",
      "category_id": "F",
      "sub_id": "F2",
      "_match_type": "exact",
      "weight": 0.6,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_040"
    },
    {
      "keyword": "清疏",
      "suggested_item": "排水系統清淤與維護管理",
      "code": "調適-水",
      "category_id": "B",
      "sub_id": "B1",
      "_match_type": "exact",
      "weight": 0.6,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [
        2
      ],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_041"
    },
    {
      "keyword": "護岸",
      "suggested_item": "自然水岸與堤岸生態化工程",
      "code": "調適-水",
      "category_id": "B",
      "sub_id": "B1",
      "_match_type": "exact",
      "weight": 0.6,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [
        7
      ],
      "synonyms": [
        "堤岸",
        "岸邊",
        "濱水"
      ],
      "negative_context": [],
      "learning_tip": "水泥護岸不代表具備調適效益，請確認是否為生態工法（NBS）。若為全面水泥硬封，則可能與韌性調適目標相衝突。",
      "trigger_id": "KW_042"
    },
    {
      "keyword": "抽水",
      "suggested_item": "滯洪池、抽水站建置與防洪改善",
      "code": "調適-水",
      "category_id": "B",
      "sub_id": "B1",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_043"
    },
    {
      "keyword": "拓寬",
      "suggested_item": "低碳路面材料或再生瀝青",
      "code": "運輸-3",
      "category_id": "A",
      "sub_id": "A2",
      "_match_type": "exact",
      "weight": 0.4,
      "purity_hint": "P4_LOW",
      "anti_pattern_ids": [
        9
      ],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_044"
    },
    {
      "keyword": "新建",
      "suggested_item": "近零碳建築技術(nZEB)",
      "code": "concept",
      "category_id": "",
      "sub_id": "",
      "_match_type": "exact",
      "weight": 0.5,
      "purity_hint": "P4_LOW",
      "anti_pattern_ids": [
        4,
        9
      ],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "命中本詞僅代表新建情境，需確認是否含近零碳建築、能效或調適設計。",
      "trigger_id": "KW_045",
      "match_type": "concept_trigger"
    },
    {
      "keyword": "宿舍",
      "suggested_item": "近零碳建築技術(nZEB)",
      "code": "住商-1",
      "category_id": "A",
      "sub_id": "A1",
      "_match_type": "exact",
      "weight": 0.6,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [
        4
      ],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_046"
    },
    {
      "keyword": "住宅",
      "suggested_item": "",
      "code": "concept",
      "category_id": "",
      "sub_id": "",
      "_match_type": "exact",
      "weight": 0.5,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [
        4
      ],
      "synonyms": [],
      "negative_context": [
        "低收入戶",
        "社會救助",
        "修繕",
        "設施改善"
      ],
      "learning_tip": "住宅相關案件需確認是否包含建築能效、節能設備或低碳建材等具體措施。",
      "trigger_id": "KW_047",
      "match_type": "concept_trigger"
    },
    {
      "keyword": "資收",
      "suggested_item": "節能減碳推廣教育宣導計畫",
      "code": "環境-5",
      "category_id": "F",
      "sub_id": "F2",
      "_match_type": "exact",
      "weight": 0.6,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_048"
    },
    {
      "keyword": "BERS",
      "suggested_item": "智慧能源管理系統（BEMS）",
      "code": "住商-5",
      "category_id": "E",
      "sub_id": "E1",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_049"
    },
    {
      "keyword": "nZEB",
      "suggested_item": "近零碳建築技術(nZEB)",
      "code": "1-11",
      "category_id": "A",
      "sub_id": "A1",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_050"
    },
    {
      "keyword": "近零碳",
      "suggested_item": "近零碳建築技術(nZEB)",
      "code": "1-11",
      "category_id": "A",
      "sub_id": "A1",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_051"
    },
    {
      "keyword": "沼氣",
      "suggested_item": "污水廠節能設備或沼氣回收",
      "code": "環境-5",
      "category_id": "B",
      "sub_id": "B2",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_052"
    },
    {
      "keyword": "SRF",
      "suggested_item": "固體再生燃料(SRF)設施或廢棄物能源化工程",
      "code": "環境-5",
      "category_id": "B",
      "sub_id": "B2",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "SRF（固體再生燃料）是廢棄物分選與能源化的重要指標，屬減緩韌域，請確認本案是否具備具體設施投入。",
      "trigger_id": "KW_053"
    },
    {
      "keyword": "竹林",
      "suggested_item": "植樹造林或都市綠化",
      "code": "農業-5",
      "category_id": "D",
      "sub_id": "D1",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_054"
    },
    {
      "keyword": "海草床",
      "suggested_item": "濕地、紅樹林或棲地復育",
      "code": "農業-7",
      "category_id": "D",
      "sub_id": "D1",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_055"
    },
    {
      "keyword": "間歇灌溉",
      "suggested_item": "水文/空氣品質科學監測與資料分析",
      "code": "農業-3",
      "category_id": "F",
      "sub_id": "F3",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_056"
    },
    {
      "keyword": "電梯",
      "suggested_item": "高能效機電設備（含電力回生電梯）",
      "code": "住商-4",
      "category_id": "A",
      "sub_id": "A1",
      "_match_type": "exact",
      "weight": 0.6,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_057"
    },
    {
      "keyword": "冷凍",
      "suggested_item": "高能效機電設備（含電力回生電梯）",
      "code": "住商-4",
      "category_id": "A",
      "sub_id": "A1",
      "_match_type": "exact",
      "weight": 0.6,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_058"
    },
    {
      "keyword": "委託營運",
      "suggested_item": "",
      "code": "concept",
      "category_id": "",
      "sub_id": "",
      "_match_type": "exact",
      "weight": 0.5,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [
        "管理案",
        "人力",
        "清潔",
        "保全",
        "一般維運"
      ],
      "learning_tip": "委託營運需確認契約是否納入節能減碳或氣候韌性KPI，方可列為氣候相關。",
      "trigger_id": "KW_059",
      "match_type": "concept_trigger"
    },
    {
      "keyword": "推進",
      "suggested_item": "地勢評估採用重力流設計（節省抽送能源）",
      "code": "水利-節能",
      "category_id": "B",
      "sub_id": "B3",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_060"
    },
    {
      "keyword": "HDPE",
      "suggested_item": "採用長壽命管材（如HDPE高密度聚乙烯管）",
      "code": "水利-材料",
      "category_id": "B",
      "sub_id": "B3",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_061"
    },
    {
      "keyword": "刨除料",
      "suggested_item": "瀝青刨除料(RAP)再利用或溫拌瀝青",
      "code": "環境-5",
      "category_id": "A",
      "sub_id": "A3",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_062"
    },
    {
      "keyword": "溫拌瀝青",
      "suggested_item": "瀝青刨除料(RAP)再利用或溫拌瀝青",
      "code": "環境-5",
      "category_id": "A",
      "sub_id": "A3",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_063"
    },
    {
      "keyword": "長軌",
      "suggested_item": "採用長軌(CWR)無縫技術與道岔優化設計",
      "code": "運輸-輕量化",
      "category_id": "C",
      "sub_id": "C3",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_064"
    },
    {
      "keyword": "道碴",
      "suggested_item": "道碴碎石區域內重複再利用",
      "code": "環境-5",
      "category_id": "C",
      "sub_id": "C3",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_065"
    },
    {
      "keyword": "無柱懸吊",
      "suggested_item": "電車線採用無柱懸吊技術（減少支柱材料）",
      "code": "運輸-輕量化",
      "category_id": "C",
      "sub_id": "C3",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_066"
    },
    {
      "keyword": "石籠",
      "suggested_item": "採用砌石、石籠等自然材料工法（減少混凝土）",
      "code": "農業-生態",
      "category_id": "D",
      "sub_id": "D3",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_067"
    },
    {
      "keyword": "砌石",
      "suggested_item": "採用砌石、石籠等自然材料工法（減少混凝土）",
      "code": "農業-生態",
      "category_id": "D",
      "sub_id": "D3",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_068"
    },
    {
      "keyword": "野溪",
      "suggested_item": "韌性野溪治理與棲地復育（優先評估 NBS 自然解方與土方平衡）",
      "code": "調適-水",
      "category_id": "B",
      "sub_id": "B1",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [
        2,
        7
      ],
      "synonyms": [
        "野溪整治",
        "崩塌地處理"
      ],
      "negative_context": [],
      "learning_tip": "注意：本案不應隨意掛載「植生碳匯」，應優先評估其防災推移與承洪韌性，並檢核是否採用生態工法（NBS）。若為水泥工法，則不具備調適效益。減碳效益應來源於工程量體縮減或土方平衡。",
      "trigger_id": "KW_069"
    },
    {
      "keyword": "農塘",
      "suggested_item": "農塘營造與蓄排水調適設施",
      "code": "調適-水",
      "category_id": "D",
      "sub_id": "D3",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_070"
    },
    {
      "keyword": "重力流",
      "suggested_item": "地勢評估採用重力流設計（節省抽送能源）",
      "code": "水利-節能",
      "category_id": "B",
      "sub_id": "B3",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_071"
    },
    {
      "keyword": "預鑄",
      "suggested_item": "模組化預鑄構件（如預鑄溝蓋、預鑄環片、系統模板）",
      "code": "環境-5",
      "category_id": "A",
      "sub_id": "A1",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_072"
    },
    {
      "keyword": "LEBR",
      "suggested_item": "取得低碳(低蘊含碳)建築標示(LEBR)或候選證書",
      "code": "住商-1",
      "category_id": "A",
      "sub_id": "A1",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_073"
    },
    {
      "keyword": "低碳建築",
      "suggested_item": "取得低碳(低蘊含碳)建築標示(LEBR)或候選證書",
      "code": "住商-1",
      "category_id": "A",
      "sub_id": "A1",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_074"
    },
    {
      "keyword": "加勁",
      "suggested_item": "地工合成加勁材擋土牆（取代傳統混凝土擋土牆）",
      "code": "農業-減碳",
      "category_id": "D",
      "sub_id": "D3",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_075"
    },
    {
      "keyword": "變頻",
      "suggested_item": "水泵、閘門採用高能源效率或變頻裝置",
      "code": "能源-節能",
      "category_id": "B",
      "sub_id": "B1",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_076"
    },
    {
      "keyword": "木排樁",
      "suggested_item": "採用砌石、石籠、木排樁等自然材料工法",
      "code": "農業-生態",
      "category_id": "D",
      "sub_id": "D3",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_077"
    },
    {
      "keyword": "低碳",
      "suggested_item": "低碳方向研判（請確認是否包含節能設備、低碳材料或運具電動化）",
      "code": "concept",
      "category_id": "",
      "sub_id": "",
      "_match_type": "exact",
      "weight": 0.7,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [],
      "synonyms": [
        "減碳"
      ],
      "negative_context": [
        "宣導",
        "活動"
      ],
      "learning_tip": "命中本詞代表具氣候概念關聯，仍需確認是否有具體可編列之減碳作為。",
      "trigger_id": "KW_078",
      "match_type": "concept_trigger"
    },
    {
      "keyword": "永續",
      "suggested_item": "永續方向研判（請確認是否具有可量化的減緩或調適措施）",
      "code": "concept",
      "category_id": "",
      "sub_id": "",
      "_match_type": "exact",
      "weight": 0.4,
      "purity_hint": "P4_LOW",
      "anti_pattern_ids": [],
      "synonyms": [
        "ESG"
      ],
      "negative_context": [
        "論壇",
        "觀光",
        "教育",
        "課程"
      ],
      "learning_tip": "永續屬高概括詞，需搭配具體減緩/調適工程或設備投資，避免僅以宣導活動列入。",
      "trigger_id": "KW_079",
      "match_type": "concept_trigger"
    },
    {
      "keyword": "溫室氣體",
      "suggested_item": "盤查與減量方向研判（請確認是否有排放盤查、設備改善或管理系統）",
      "code": "concept",
      "category_id": "",
      "sub_id": "",
      "_match_type": "exact",
      "weight": 0.7,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [
        "GHG"
      ],
      "negative_context": [
        "宣導"
      ],
      "learning_tip": "命中本詞通常具氣候關聯，但仍須確認是否有具體支出工項。",
      "trigger_id": "KW_080",
      "match_type": "concept_trigger"
    },
    {
      "keyword": "氣候變遷",
      "suggested_item": "減緩/調適方向分流（請確認本案主軸）",
      "code": "concept",
      "category_id": "",
      "sub_id": "",
      "_match_type": "exact",
      "weight": 0.7,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [],
      "synonyms": [
        "氣候"
      ],
      "negative_context": [],
      "learning_tip": "此詞為總括概念，建議下一步確認屬減緩、調適或研究規劃。",
      "trigger_id": "KW_081",
      "match_type": "concept_trigger"
    },
    {
      "keyword": "調適",
      "suggested_item": "調適方向研判（請確認是否為防洪、降溫、韌性等具體作為）",
      "code": "concept",
      "category_id": "",
      "sub_id": "",
      "_match_type": "exact",
      "weight": 0.7,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [],
      "synonyms": [
        "韌性"
      ],
      "negative_context": [],
      "learning_tip": "命中本詞代表調適導向（含研究/規劃案），仍需確認是否有可拆分之具體調適支出。",
      "trigger_id": "KW_082",
      "match_type": "concept_trigger"
    },
    {
      "keyword": "購置腳踏車",
      "suggested_item": "補助民眾購置自行車或電動自行車",
      "code": "運輸-1",
      "category_id": "C",
      "sub_id": "C4",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [
        "購置自行車",
        "補助腳踏車",
        "補助自行車"
      ],
      "negative_context": [
        "自行車道",
        "步道",
        "車道建置"
      ],
      "learning_tip": "命中「腳踏車」多為補助購置情境，建議對應 C4 獎補助工項而非自行車道工程。",
      "trigger_id": "KW_083"
    },
    {
      "keyword": "電動機車",
      "suggested_item": "補助民眾購置電動機車",
      "code": "運輸-2",
      "category_id": "C",
      "sub_id": "C4",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [
        "電動摩托車",
        "電動輕型機車",
        "電動重機",
        "購置機車",
        "補助機車",
        "補助電動車"
      ],
      "negative_context": [
        "公車",
        "巴士",
        "公務車"
      ],
      "learning_tip": "命中「電動機車」多為補助民眾購置情境，對應 C4 獎補助工項。",
      "trigger_id": "KW_084"
    },
    {
      "keyword": "電動自行車",
      "suggested_item": "補助民眾購置自行車或電動自行車",
      "code": "運輸-1",
      "category_id": "C",
      "sub_id": "C4",
      "_match_type": "exact",
      "weight": 0.9,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [
        "電輔車",
        "電動腳踏車",
        "購置電動自行車",
        "補助電動自行車"
      ],
      "negative_context": [],
      "learning_tip": "電動自行車補助屬低碳運具普及，對應 C4 獎補助工項。",
      "trigger_id": "KW_085"
    },
    {
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [
        "糞尿資源化",
        "畜牧糞尿資源化"
      ],
      "negative_context": [],
      "learning_tip": "",
      "keyword": "畜牧糞尿",
      "suggested_item": "畜牧糞尿氨氮回收與沼氣發電",
      "code": "環境-5",
      "category_id": "B",
      "sub_id": "B2",
      "trigger_id": "KW_086"
    },
    {
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [
        "沼液",
        "沼渣"
      ],
      "negative_context": [],
      "learning_tip": "",
      "keyword": "沼液沼渣",
      "suggested_item": "補助農民或畜牧業者進行沼氣回收或沼氣發電（獎補助型）",
      "code": "農業-1",
      "category_id": "B",
      "sub_id": "B2",
      "trigger_id": "KW_091"
    },
    {
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [],
      "negative_context": [],
      "learning_tip": "",
      "keyword": "養豬場廢水",
      "suggested_item": "畜牧糞尿氨氮回收與沼氣發電",
      "code": "環境-5",
      "category_id": "B",
      "sub_id": "B2",
      "trigger_id": "KW_092"
    },
    {
      "keyword": "資源化",
      "suggested_item": "",
      "code": "concept",
      "category_id": "",
      "sub_id": "",
      "_match_type": "exact",
      "weight": 0.6,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [],
      "synonyms": [
        "再利用",
        "循環利用"
      ],
      "negative_context": [
        "宣導",
        "活動"
      ],
      "learning_tip": "命中本詞代表可能涉及循環經濟或減廢措施，需確認是否有具體工程或設備投入。",
      "match_type": "concept_trigger",
      "trigger_id": "KW_093"
    },
    {
      "keyword": "生質能",
      "suggested_item": "",
      "code": "concept",
      "category_id": "",
      "sub_id": "",
      "_match_type": "exact",
      "weight": 0.7,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [
        "生質能源",
        "生質料源"
      ],
      "negative_context": [
        "宣導",
        "活動"
      ],
      "learning_tip": "請確認是否涉及廢棄物資源化、生質能利用或能源轉換等具體作為。",
      "match_type": "concept_trigger",
      "trigger_id": "KW_095"
    },
    {
      "keyword": "廢棄物再利用",
      "suggested_item": "",
      "code": "concept",
      "category_id": "",
      "sub_id": "",
      "_match_type": "exact",
      "weight": 0.7,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [
        "廢棄物資源化"
      ],
      "negative_context": [
        "宣導",
        "活動"
      ],
      "learning_tip": "請確認是否涉及能量回收、再利用或減少最終處置之具體措施。",
      "match_type": "concept_trigger",
      "trigger_id": "KW_096"
    },
    {
      "keyword": "廊道",
      "suggested_item": "水綠廊道或生態廊道建置",
      "code": "農業-7",
      "category_id": "D",
      "sub_id": "D1",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [
        "水綠廊道",
        "景觀廊道",
        "廊帶"
      ],
      "negative_context": [],
      "learning_tip": "水綠廊道常結合降溫、滯洪與生態功能，屬高品質調適案件。",
      "trigger_id": "KW_097"
    },
    {
      "keyword": "熱島",
      "suggested_item": "都市熱島效應緩解（降溫工法）",
      "code": "住商-2",
      "category_id": "A",
      "sub_id": "A2",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [
        "熱島效應",
        "都市降溫"
      ],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_098"
    },
    {
      "keyword": "出流管制",
      "suggested_item": "基地出流管制與透水韌性提升",
      "code": "調適-水",
      "category_id": "B",
      "sub_id": "B1",
      "_match_type": "exact",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [
        "逕流分擔"
      ],
      "negative_context": [],
      "learning_tip": "",
      "trigger_id": "KW_099"
    },
    {
      "keyword": "水環境",
      "suggested_item": "水環境改善、生態護岸或水質處理",
      "code": "調適-水",
      "category_id": "B",
      "sub_id": "B1",
      "_match_type": "exact",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [
        "水環境改善",
        "水質淨化"
      ],
      "negative_context": [],
      "learning_tip": "水環境工程常結合生態護岸與防洪調適，屬高品質水利調適案件。",
      "trigger_id": "KW_100"
    },
    {
      "keyword": "海堤生態化",
      "suggested_item": "海岸生態防護與海堤生態化工程(Coastal GI)",
      "code": "調適-海岸",
      "category_id": "B",
      "sub_id": "B1",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [
        7
      ],
      "synonyms": [
        "海岸防護NBS",
        "海岸帶管理"
      ],
      "negative_context": [],
      "learning_tip": "海岸生態化工程通常具備減災與維護生物多樣性雙重價值，屬高純度調適案件。",
      "trigger_id": "KW_101"
    },
    {
      "keyword": "熱危害",
      "suggested_item": "高溫健康防護與脆弱族群氣候照顧計畫",
      "code": "調適-健康",
      "category_id": "G",
      "sub_id": "G3",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [
        10
      ],
      "synonyms": [
        "高溫防護",
        "熱中暑預警"
      ],
      "negative_context": [],
      "learning_tip": "高溫健康調適屬於社會韌性領域，通常涉及脆弱族群（高齡、戶外工作者）的調適作為。",
      "trigger_id": "KW_102"
    },
    {
      "keyword": "電網韌性",
      "suggested_item": "關鍵基礎設施氣候韌性提升（供電穩健化）",
      "code": "調適-設施",
      "category_id": "B",
      "sub_id": "B3",
      "weight": 0.8,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [],
      "synonyms": [
        "變電站提升",
        "電網強韌"
      ],
      "negative_context": [],
      "learning_tip": "關鍵基礎設施（能源、通訊）的耐災強化是調適行動方案中的關鍵指標。",
      "trigger_id": "KW_103"
    },
    {
      "keyword": "低碳工業",
      "suggested_item": "中小企業低碳轉型與製程減碳輔導計畫",
      "code": "工業-1",
      "category_id": "E",
      "sub_id": "E2",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [
        "製程減碳",
        "設備能效提升"
      ],
      "negative_context": [],
      "learning_tip": "工業部門減緩重點在於動力傳送、製程優化與系統節能。",
      "trigger_id": "KW_104"
    },
    {
      "keyword": "廢棄物能源化",
      "suggested_item": "廢棄物分選、能源化與資源循環設施",
      "code": "環境-5",
      "category_id": "B",
      "sub_id": "B2",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "synonyms": [
        "廢棄物發電",
        "SRF設施"
      ],
      "negative_context": [],
      "learning_tip": "廢棄物能源化(WTE)是資源循環與能源轉型的重疊領域，屬高純度減緩案件。",
      "trigger_id": "KW_105"
    },
    {
      "keyword": "灌溉",
      "suggested_item": "智慧灌溉節水系統或農業管路改善（農業調適）",
      "code": "農業-3",
      "category_id": "D",
      "sub_id": "D3",
      "_match_type": "exact",
      "weight": 0.7,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [],
      "synonyms": [
        "滴灌",
        "噴灌",
        "節水灌溉",
        "農業用水"
      ],
      "negative_context": [
        "宣導",
        "補助申請",
        "教育"
      ],
      "learning_tip": "農業灌溉節水是因應乾旱氣候的重要調適手段。請確認本案是否具備智慧化管理或節水設施投入，而非單純維護既有水路。",
      "trigger_id": "KW_106"
    },
    {
      "keyword": "邊坡",
      "suggested_item": "邊坡穩定與坡地生態防災工程（優先評估 NBS 工法）",
      "code": "調適-水",
      "category_id": "B",
      "sub_id": "B1",
      "_match_type": "exact",
      "weight": 0.6,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [
        7
      ],
      "synonyms": [
        "坡地",
        "坡腳",
        "坡面",
        "山坡地"
      ],
      "negative_context": [],
      "learning_tip": "邊坡治理與野溪治理類似，需區分 NBS 生態工法（如植生護坡、石籠）與水泥噴漿等灰色工法。後者不具備調適效益，且可能增加下游洪峰。",
      "trigger_id": "KW_107"
    },
    {
      "keyword": "遮蔭",
      "suggested_item": "行人遮蔭設施或騎樓連通（高溫健康調適）",
      "code": "調適-健康",
      "category_id": "G",
      "sub_id": "G3",
      "_match_type": "exact",
      "weight": 0.7,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "synonyms": [
        "騎樓",
        "涼亭",
        "遮陽棚",
        "行人庇護"
      ],
      "negative_context": [],
      "learning_tip": "都市高溫調適除熱島管理外，行人層級的遮蔭設施是提升脆弱族群熱舒適的重要公共投資，對應調適行動方案中的健康領域。",
      "trigger_id": "KW_108"
    }
  ],
  "exclusion_keywords": [
    "法律",
    "訴願",
    "審計",
    "精算",
    "疫苗",
    "接種",
    "防毒",
    "頻寬",
    "監視",
    "保全",
    "影印",
    "粉刷",
    "印製",
    "宣傳品"
  ],
  "keyword_logic": [
    {
      "triggers": [
        "租賃",
        "公務車"
      ],
      "suggested_item": "車輛租賃低碳化（限電動車/油電車）",
      "category_id": "C",
      "sub_id": "C2",
      "_match_type": "logic",
      "note": "需同時出現：租賃＋公務車",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "trigger_id": "KWL_01"
    },
    {
      "triggers": [
        "評估",
        "規劃",
        "徵收"
      ],
      "suggested_item": "氣候變遷風險與韌性評估",
      "category_id": "F",
      "sub_id": "F1",
      "_match_type": "logic",
      "note": "需同時出現：評估＋規劃＋徵收",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "trigger_id": "KWL_02"
    },
    {
      "triggers": [
        "資訊",
        "系統"
      ],
      "suggested_item": "災害預警或智慧水網監測系統",
      "category_id": "F",
      "sub_id": "F2",
      "note": "提示排除一般行政 IT 維運系統",
      "_match_type": "logic",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "trigger_id": "KWL_03"
    },
    {
      "triggers": [
        "出流管制",
        "水保"
      ],
      "suggested_item": "防洪排水與滯洪設施",
      "category_id": "B",
      "sub_id": "B1",
      "_match_type": "logic",
      "note": "需同時出現：出流管制＋水保",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "trigger_id": "KWL_04"
    },
    {
      "triggers": [
        "畜牧",
        "糞尿"
      ],
      "suggested_item": "畜牧糞尿氨氮回收與沼氣發電",
      "category_id": "B",
      "sub_id": "B2",
      "_match_type": "logic",
      "note": "需同時出現：畜牧＋糞尿",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "trigger_id": "KWL_05"
    },
    {
      "triggers": [
        "沼液",
        "沼渣"
      ],
      "suggested_item": "補助農民或畜牧業者進行沼氣回收或沼氣發電（獎補助型）",
      "category_id": "B",
      "sub_id": "B2",
      "_match_type": "logic",
      "note": "需同時出現：沼液＋沼渣",
      "weight": 1.0,
      "purity_hint": "P1_HIGH_PURITY",
      "anti_pattern_ids": [],
      "trigger_id": "KWL_06"
    },
    {
      "triggers": [
        "養豬場",
        "資源化"
      ],
      "suggested_item": "補助農民或畜牧業者進行沼氣回收或沼氣發電（獎補助型）",
      "category_id": "B",
      "sub_id": "B2",
      "_match_type": "logic",
      "note": "需同時出現：養豬場＋資源化",
      "weight": 0.8,
      "purity_hint": "P2_HIGH_RELEVANCE",
      "anti_pattern_ids": [],
      "trigger_id": "KWL_07"
    },
    {
      "triggers": [
        "生質",
        "能源"
      ],
      "suggested_item": "",
      "category_id": "",
      "sub_id": "",
      "_match_type": "logic",
      "note": "生質能相關語意組合，請人工確認是否具體氣候作為",
      "weight": 0.6,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [],
      "trigger_id": "KWL_08"
    },
    {
      "triggers": [
        "資源化",
        "設施"
      ],
      "suggested_item": "",
      "category_id": "",
      "sub_id": "",
      "_match_type": "logic",
      "note": "資源化設施語意組合，請確認是否有工程或設備投入",
      "weight": 0.6,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [],
      "trigger_id": "KWL_09"
    },
    {
      "triggers": [
        "廢棄物",
        "再利用"
      ],
      "suggested_item": "",
      "category_id": "",
      "sub_id": "",
      "_match_type": "logic",
      "note": "廢棄物再利用語意組合，請確認是否為具體減廢/能源回收措施",
      "weight": 0.6,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [],
      "trigger_id": "KWL_10"
    },
    {
      "triggers": [
        "廚餘",
        "處理"
      ],
      "suggested_item": "",
      "category_id": "",
      "sub_id": "",
      "_match_type": "logic",
      "note": "廚餘處理語意組合，請確認是否涉及能源化或資源循環設施",
      "weight": 0.6,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [],
      "trigger_id": "KWL_11"
    },
    {
      "triggers": [
        "有機廢棄物",
        "利用"
      ],
      "suggested_item": "",
      "category_id": "",
      "sub_id": "",
      "_match_type": "logic",
      "note": "有機廢棄物利用語意組合，請確認是否有具體氣候效益",
      "weight": 0.6,
      "purity_hint": "P3_PARTIAL",
      "anti_pattern_ids": [],
      "trigger_id": "KWL_12"
    }
  ]
}